#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'colorize'
require 'optparse'
require 'redlog'

ARGV << '-h' if ARGV.empty? # with no arguments show banner

options = {}
OptionParser.new do |opts|
  opts.banner = Redlog::ASCII.banner
  opts.banner += "Fast and easy CLI for the Redmine project management tool\n\t".colorize(:red)
  opts.banner += "Usage: redlog '[title]' [options]\n\n".colorize(:light_magenta)
  opts.banner += 'Options:'

  opts.on('-l', '--log TIME', 'Logs time spent into issue (taken in hours)')

  opts.on('-d', '--description DESC', 'Add description to issue')
end.parse! into: options

title = ARGV[0]

cli = Redlog::CLI.new

case title
when 'setup'
  creds_hash = cli.setup_prompt
  Redlog::Setup.setup_credentials(creds_hash)
  cli.log 'Congratulations, Redlog is set up and ready to roll!', :success

when 'preferences'
  # TODO: Add preference change

else
  output = cli.execute(title, options)
  cli.log output
end
